<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" tests="15" skipped="0" failures="0" errors="0" timestamp="2021-05-09T12:42:10" hostname="wangweilidembp" time="0.079">
  <properties/>
  <testcase name="testDescriptionNotNull()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.015"/>
  <testcase name="testGetMBeanAttributeInfo()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.005"/>
  <testcase name="testSetAttribute()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testAttributeInfoHasDescriptors()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testGetMBeanInfo()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testGetMBeanOperationInfo()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.005"/>
  <testcase name="testRegisterOperations()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.005"/>
  <testcase name="testRegisterAttributes()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.005"/>
  <testcase name="testNotificationMetadata()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testAttributeHasCorrespondingOperations()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.006"/>
  <testcase name="testMBeanRegistration()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testGetAttribute()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testOperationInvocation()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testGetAgeIsReadOnly()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <testcase name="testNickNameIsExposed()" classname="org.springframework.jmx.export.assembler.MethodExclusionMBeanInfoAssemblerMappedTests" time="0.004"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[May 09, 2021 8:42:10 P.M. ClientIntermediary close
INFO: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

May 09, 2021 8:42:10 P.M. ClientIntermediary close
INFO: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

]]></system-err>
</testsuite>
